// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/agents": {
            "get": {
                "description": "Returns all agents that have registered with the server.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "List all enrolled agents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.Agent"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/agents/register": {
            "post": {
                "description": "Agents call this on startup and periodically to register themselves with the server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Register or heartbeat an agent",
                "parameters": [
                    {
                        "description": "Agent registration payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.RegisterAgentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Agent"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/agents/{agentID}": {
            "get": {
                "description": "Returns a single agent's details.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Get agent by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Agent"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "description": "Removes an agent from the fleet inventory.",
                "tags": [
                    "agents"
                ],
                "summary": "Remove an agent",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/agents/{agentID}/force-update": {
            "post": {
                "description": "Queues an update for the specified agent which will be delivered on its next heartbeat.",
                "tags": [
                    "agents"
                ],
                "summary": "Force an agent to update immediately",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/agents/{agentID}/lab": {
            "put": {
                "description": "Associates an agent with a lab/room for grouping.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "agents"
                ],
                "summary": "Assign agent to a lab",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Agent ID",
                        "name": "agentID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Lab assignment",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.AssignLabRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/installers/generate": {
            "post": {
                "description": "Returns a download URL for the latest pre-built MSI with an msiexec command.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "installers"
                ],
                "summary": "Generate a custom MSI installer",
                "parameters": [
                    {
                        "description": "Installer configuration",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.GenerateInstallerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/installers/latest": {
            "get": {
                "responses": {}
            }
        },
        "/api/v1/labs": {
            "get": {
                "description": "Returns all configured labs/rooms.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "labs"
                ],
                "summary": "List all labs",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.Lab"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new lab or room grouping for agents.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "labs"
                ],
                "summary": "Create a lab/room",
                "parameters": [
                    {
                        "description": "Lab details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateLabRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/store.Lab"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/labs/{labID}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "labs"
                ],
                "summary": "Get lab by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lab ID",
                        "name": "labID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.Lab"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "labs"
                ],
                "summary": "Update a lab",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lab ID",
                        "name": "labID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Updated lab details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.CreateLabRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "tags": [
                    "labs"
                ],
                "summary": "Delete a lab",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Lab ID",
                        "name": "labID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/mappings": {
            "get": {
                "description": "Returns all software name mappings for admin management.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mappings"
                ],
                "summary": "List all software mappings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.SoftwareMapping"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Updates an existing exe-to-display-name mapping (upsert by exeName).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mappings"
                ],
                "summary": "Update a software mapping",
                "parameters": [
                    {
                        "description": "Mapping details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.MappingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Adds a new exe-to-display-name mapping.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mappings"
                ],
                "summary": "Create a software mapping",
                "parameters": [
                    {
                        "description": "Mapping details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.MappingRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/mappings/agent": {
            "get": {
                "description": "Returns all software mappings in the format agents expect (software-map.json compatible). Agents poll this endpoint via mappingUpdateURL.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mappings"
                ],
                "summary": "Get mappings for agents",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/mappings/categories": {
            "get": {
                "description": "Returns the closed set of categories the portal/CLI accept when creating or editing a mapping.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mappings"
                ],
                "summary": "List valid mapping categories",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/mappings/{mappingID}": {
            "delete": {
                "tags": [
                    "mappings"
                ],
                "summary": "Delete a software mapping",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Mapping ID",
                        "name": "mappingID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/mappings/{mappingID}/ignore": {
            "patch": {
                "description": "Sets or clears the ignored flag for a mapping without changing other fields.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mappings"
                ],
                "summary": "Toggle mapping ignored state",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Mapping ID",
                        "name": "mappingID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Ignored state {ignored: bool}",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/reports/active-users": {
            "get": {
                "description": "Returns users with active sessions right now.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Currently active users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/api/v1/reports/avg-session-time": {
            "get": {
                "description": "Returns top N users ranked by average session duration in minutes. Users with fewer than minLoginsForAvgSession logins in the window are omitted — too small a sample to average meaningfully.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Average session duration per user",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific machine",
                        "name": "hostname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific lab name",
                        "name": "lab",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/reports/bottom-apps-by-foreground": {
            "get": {
                "description": "Returns bottom (least used) applications by foreground time.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Bottom applications by foreground time",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "json",
                        "description": "Output format: json or csv",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/reports/bottom-apps-by-launches": {
            "get": {
                "description": "Returns bottom (least used) applications by launch count.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Bottom applications by launch count",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "json",
                        "description": "Output format: json or csv",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/reports/summary": {
            "get": {
                "description": "Returns high-level fleet stats: total agents, online count, labs, mappings.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Fleet summary",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.SummaryResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/reports/top-apps": {
            "get": {
                "description": "Returns the top applications by total usage seconds over the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Top applications by usage time",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 20,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "json",
                        "description": "Output format: json or csv",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/reports/top-apps-by-elevations": {
            "get": {
                "description": "Returns top applications by privilege-elevation launch count over the given time range (UAC on Windows, sudo/admin authorization on macOS). Data is typically sparse.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Top applications by UAC elevation count",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range (e.g. 24h, 7d, 30d)",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific machine",
                        "name": "hostname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific lab name",
                        "name": "lab",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "json",
                        "description": "Output format: json or csv",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/reports/top-apps-by-foreground": {
            "get": {
                "description": "Returns top applications by total foreground (active) time.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Top applications by foreground time",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "json",
                        "description": "Output format: json or csv",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/reports/top-apps-by-launches": {
            "get": {
                "description": "Returns top applications by total launch count over the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Top applications by launch count",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range (e.g. 24h, 7d, 30d)",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "json",
                        "description": "Output format: json or csv",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/reports/top-devices-by-sessions": {
            "get": {
                "description": "Returns the top N hostnames ranked by user login count over the time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Top devices by session count",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific machine",
                        "name": "hostname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific lab name",
                        "name": "lab",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/reports/top-labs-by-utilization": {
            "get": {
                "description": "Returns labs ranked by average utilization % over the time range, top 10.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Top labs by average utilization",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range (e.g. 24h, 7d, 30d)",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom range start (unix or RFC3339)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom range end (unix or RFC3339)",
                        "name": "end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.labAvgUtilization"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/reports/top-users-by-elevations": {
            "get": {
                "description": "Returns the top N users ranked by privilege-elevation launches over the time range (UAC on Windows, sudo/admin authorization on macOS). Data is typically sparse.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Top users by UAC elevation count",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific machine",
                        "name": "hostname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific lab name",
                        "name": "lab",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/reports/top-users-by-logins": {
            "get": {
                "description": "Returns the top N users ranked by total login sessions over the time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Top users by login count",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific machine",
                        "name": "hostname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific lab name",
                        "name": "lab",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/reports/top-users-by-session-time": {
            "get": {
                "description": "Returns the top N users ranked by total session hours over the time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Top users by total session time",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Max results",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific machine",
                        "name": "hostname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific lab name",
                        "name": "lab",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/api/v1/reports/usage-by-lab": {
            "get": {
                "description": "Returns total app usage hours grouped by lab over the given time range.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Usage breakdown by lab",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range (e.g. 24h, 7d)",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific machine hostname",
                        "name": "hostname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific lab name",
                        "name": "lab",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom range start (unix or RFC3339)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom range end (unix or RFC3339)",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "json",
                        "description": "Output format: json or csv",
                        "name": "format",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "502": {
                        "description": "Bad Gateway",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/reports/utilization-over-time": {
            "get": {
                "description": "Returns per-lab utilization percentage as a time series.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "reports"
                ],
                "summary": "Machine utilization % over time",
                "parameters": [
                    {
                        "type": "string",
                        "default": "24h",
                        "description": "Time range (e.g. 24h, 7d, 30d)",
                        "name": "range",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific machine",
                        "name": "hostname",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter to a specific lab",
                        "name": "lab",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom range start (unix or RFC3339)",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Custom range end (unix or RFC3339)",
                        "name": "end",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.utilizationResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/settings": {
            "get": {
                "description": "Returns global configuration for agents and server.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Get system settings",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/store.SystemSettings"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Updates global configuration for agents and server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "settings"
                ],
                "summary": "Update system settings",
                "parameters": [
                    {
                        "description": "Settings payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/store.SystemSettings"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/users": {
            "get": {
                "description": "Returns every username Prometheus has recorded, grouped by the canonical identity it resolves to, with its ignore state and recent session hours.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List users seen in metrics",
                "parameters": [
                    {
                        "type": "string",
                        "default": "30d",
                        "description": "Time range for session hours",
                        "name": "range",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.DiscoveredUser"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/users/ignore": {
            "post": {
                "description": "Marks a username as ignored, creating the rule if needed. Used by the ignore action on the users and reports pages.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Ignore a user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/users/mappings": {
            "get": {
                "description": "Returns all user ignore/correlation rules.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "List user rules",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/store.UserMapping"
                            }
                        }
                    }
                }
            },
            "put": {
                "description": "Adds or replaces the rule for a username pattern. Patterns may contain \"*\" wildcards and match case-insensitively against the raw username and its canonical form.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Create or update a user rule",
                "parameters": [
                    {
                        "description": "Rule details",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.UserMappingRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/users/mappings/{mappingID}": {
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Delete a user rule",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Rule ID",
                        "name": "mappingID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/users/mappings/{mappingID}/ignore": {
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Toggle a user rule's ignored flag",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Rule ID",
                        "name": "mappingID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/users/policy": {
            "get": {
                "description": "Returns the policy agents apply at collection time: domain stripping, ignore patterns, and alias mappings. Agents also receive this in the registration response.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Get the effective user policy",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.AgentUserPolicy"
                        }
                    }
                }
            },
            "put": {
                "description": "Sets whether domain prefixes and UPN suffixes are stripped when correlating identities across Windows and macOS.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Update user policy options",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/api/v1/version": {
            "get": {
                "description": "Returns the running server's version, git commit, build date, and Go runtime version.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "meta"
                ],
                "summary": "Server build information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.buildInfoResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.AgentUserPolicy": {
            "type": "object",
            "properties": {
                "aliases": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "ignorePatterns": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "stripDomain": {
                    "type": "boolean"
                }
            }
        },
        "api.AssignLabRequest": {
            "type": "object",
            "properties": {
                "labId": {
                    "type": "string"
                }
            }
        },
        "api.CreateLabRequest": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "room": {
                    "type": "string"
                }
            }
        },
        "api.DiscoveredUser": {
            "type": "object",
            "properties": {
                "activeNow": {
                    "type": "boolean"
                },
                "canonicalUser": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "ignored": {
                    "type": "boolean"
                },
                "matchedRule": {
                    "type": "string"
                },
                "rawUsers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "ruleId": {
                    "type": "integer"
                },
                "sessionHours": {
                    "type": "number"
                }
            }
        },
        "api.GenerateInstallerRequest": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "room": {
                    "type": "string"
                },
                "serverAddress": {
                    "type": "string"
                }
            }
        },
        "api.MappingRequest": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "exeName": {
                    "type": "string"
                },
                "family": {
                    "type": "string"
                },
                "ignored": {
                    "type": "boolean"
                },
                "publisher": {
                    "type": "string"
                }
            }
        },
        "api.RegisterAgentRequest": {
            "type": "object",
            "properties": {
                "agentVersion": {
                    "type": "string"
                },
                "building": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ipAddress": {
                    "type": "string"
                },
                "osVersion": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "room": {
                    "type": "string"
                }
            }
        },
        "api.SummaryResponse": {
            "type": "object",
            "properties": {
                "onlineAgents": {
                    "type": "integer"
                },
                "totalAgents": {
                    "type": "integer"
                },
                "totalLabs": {
                    "type": "integer"
                },
                "totalMappings": {
                    "type": "integer"
                }
            }
        },
        "api.UserMappingRequest": {
            "type": "object",
            "properties": {
                "canonicalUser": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "ignored": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                },
                "pattern": {
                    "type": "string"
                }
            }
        },
        "api.buildInfoResponse": {
            "type": "object",
            "properties": {
                "buildDate": {
                    "type": "string"
                },
                "gitCommit": {
                    "type": "string"
                },
                "goVersion": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "api.labAvgUtilization": {
            "type": "object",
            "properties": {
                "avgPct": {
                    "type": "number"
                },
                "lab": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api.utilizationPoint": {
            "type": "object",
            "properties": {
                "t": {
                    "type": "integer"
                },
                "v": {
                    "type": "number"
                }
            }
        },
        "api.utilizationResponse": {
            "type": "object",
            "properties": {
                "series": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.utilizationSeries"
                    }
                },
                "step": {
                    "type": "integer"
                }
            }
        },
        "api.utilizationSeries": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.utilizationPoint"
                    }
                },
                "lab": {
                    "type": "string"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "store.Agent": {
            "type": "object",
            "properties": {
                "agentVersion": {
                    "type": "string"
                },
                "building": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "hostname": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ipAddress": {
                    "type": "string"
                },
                "labId": {
                    "type": "string"
                },
                "lastSeen": {
                    "type": "string"
                },
                "osVersion": {
                    "type": "string"
                },
                "pendingUpdate": {
                    "type": "string"
                },
                "port": {
                    "type": "integer"
                },
                "room": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "store.Lab": {
            "type": "object",
            "properties": {
                "building": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "room": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "store.SoftwareMapping": {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "exeName": {
                    "type": "string"
                },
                "family": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ignored": {
                    "type": "boolean"
                },
                "publisher": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        },
        "store.SystemSettings": {
            "type": "object",
            "properties": {
                "heartbeatIntervalSeconds": {
                    "type": "integer"
                },
                "maintenanceWindowEnd": {
                    "description": "HH:mm",
                    "type": "string"
                },
                "maintenanceWindowStart": {
                    "description": "HH:mm",
                    "type": "string"
                },
                "minAgentVersion": {
                    "type": "string"
                },
                "staleTimeoutDays": {
                    "type": "integer"
                },
                "updateIntervalSeconds": {
                    "type": "integer"
                }
            }
        },
        "store.UserMapping": {
            "type": "object",
            "properties": {
                "canonicalUser": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "displayName": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "ignored": {
                    "type": "boolean"
                },
                "notes": {
                    "type": "string"
                },
                "pattern": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.3",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "OpenLabStats Server API",
	Description:      "Central management server for the OpenLabStats fleet. Manages agent enrollment, software mappings, lab groupings, and reporting.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
